### PR TITLE
Day 1

### PR DESCRIPTION
**Pull request by delbaoliveira**
Adding folders and files.
Setting up less styles 👇

### CODE REVIEW

**Comment by delbaoliveira** [comment]
Home page components 👇

**Comment by delbaoliveira** [comment]
Home page - Intro component 👇

**Comment by delbaoliveira** [comment]
Home page - Featured 👇

**Comment by delbaoliveira** [comment]
Home page - Footer 👇

**Comment by delbaoliveira** [comment]
Home page - Navigation 👇

**Comment by delbaoliveira** [comment]
wow! thank you @Velsu :)

**Comment by Velsu** [comment]
Don't forget to pull the changes into Your local master branch before making new one 👍

**Pull request merged**
